from __future__ import annotations

import argparse
import csv
from collections.abc import Iterator
from pathlib import Path
from typing import Any

from dateutil.parser import parse as parse_datetime
from loguru import logger
from sqlalchemy import text

from archive_etl.attachments.manifest import FlexibleManifestStore, ManifestStore
from archive_etl.attachments.models import (
    ArchiveCounts,
    AttachmentRecord,
    sanitize_file_name,
    utc_now,
)
from archive_etl.attachments.plugins.base import AttachmentPlugin
from archive_etl.upload.migrations import apply_migrations
from archive_etl.upload.postgres import create_postgres_engine

# Maps the generic runner's own hardcoded 3-state vocabulary
# ("ARCHIVED"/"MISSING"/"FAILED" - see runner.py's process_attachment,
# not plugin-configurable) onto archive.proposal_attachment's own
# upload_status CHECK constraint. NOT_REQUESTED (the metadata loader's
# own default - see load_proposals_from_csv.py's
# upsert_proposal_attachments) and IN_PROGRESS (reserved for a future
# concurrent/async runner - this synchronous runner never writes it,
# the same "future sprint, not this loader" precedent
# archive.attachment_object.upload_status already established for
# Award) are never produced by sync_postgres below.
_RUNNER_STATUS_TO_UPLOAD_STATUS = {
    "ARCHIVED": "UPLOADED",
    "MISSING": "MISSING_SOURCE",
    "FAILED": "FAILED",
}


def _optional_int(value: str | None) -> int | None:
    if value is None or not str(value).strip():
        return None
    return int(value)


def _parse_manifest_timestamp(value: str | None):
    if not value:
        return None
    return parse_datetime(value)


class ProposalAttachmentPlugin(AttachmentPlugin):
    module_name = "proposal"
    # PROPOSAL_ATTACHMENTS.FILE_DATA_ID -> KCOEUS.FILE_DATA.ID, the same
    # shape Subaward uses (FileDataBlobReader, the base class's own
    # default create_blob_reader() - never overridden here) - NOT
    # Award/Negotiation/Protocol's ATTACHMENT_FILE/FILE_ID shape. See
    # docs/kuali-business-rules/InstitutionalProposal.md's Attachments
    # section.
    default_metadata_csv = (
        Path.home() / "Downloads" / "proposal_attachments.csv"
    )
    default_manifest = (
        Path(__file__).resolve().parents[3]
        / "exports"
        / "proposals"
        / "proposal_attachment_manifest.sqlite3"
    )
    default_s3_prefix = "proposal"
    bucket_environment_variable = "PROPOSAL_ATTACHMENT_S3_BUCKET"
    prefix_environment_variable = "PROPOSAL_ATTACHMENT_S3_PREFIX"
    sse_environment_variable = "PROPOSAL_ATTACHMENT_SSE"
    kms_environment_variable = "PROPOSAL_ATTACHMENT_KMS_KEY_ID"

    def create_manifest(self, path: Path) -> FlexibleManifestStore:
        return FlexibleManifestStore(path)

    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        parser.add_argument("--proposal-id", type=int)

    def selected_record_id(self, args: argparse.Namespace) -> int | None:
        return args.proposal_id

    def iter_records(
        self,
        path: Path,
        record_id: int | None,
        limit: int | None,
    ) -> Iterator[AttachmentRecord]:
        # CSV is generated by export_proposal_attachments_csv.py
        # directly from archive.proposal_attachment - already
        # Oracle-accurate metadata, no second Oracle round trip and no
        # manual export step, unlike Subaward/Award's own CSVs.
        required = {
            "proposal_attachment_id",
            "proposal_id",
            "proposal_number",
            "sequence_number",
            "attachment_number",
            "attachment_title",
            "file_name",
            "file_data_id",
            "content_type",
            "comments",
            "document_status_code",
            "source_update_timestamp",
        }
        emitted = 0
        with path.open(newline="", encoding="utf-8-sig") as stream:
            reader = csv.DictReader(stream)
            if reader.fieldnames is None:
                raise RuntimeError(f"{path} has no CSV header")
            reader.fieldnames = [
                name.strip().lower() for name in reader.fieldnames
            ]
            missing = sorted(required - set(reader.fieldnames))
            if missing:
                raise RuntimeError(
                    f"{path.name} is missing columns: "
                    + ", ".join(missing)
                )
            for row in reader:
                proposal_id = int(row["proposal_id"])
                if record_id is not None and proposal_id != record_id:
                    continue
                if limit is not None and emitted >= limit:
                    break
                emitted += 1
                yield AttachmentRecord(
                    module=self.module_name,
                    record_id=proposal_id,
                    attachment_id=int(row["proposal_attachment_id"]),
                    file_data_id=row["file_data_id"].strip() or None,
                    original_file_name=row["file_name"].strip() or None,
                    mime_type=row["content_type"].strip() or None,
                    attributes={
                        "business_key": row["proposal_number"].strip(),
                        "sequence_number": int(row["sequence_number"]),
                        "attachment_number":
                            _optional_int(row["attachment_number"]),
                        "title": row["attachment_title"].strip() or None,
                        "comments": row["comments"].strip() or None,
                        "document_status_code":
                            row["document_status_code"].strip() or None,
                        "source_update_timestamp":
                            row["source_update_timestamp"].strip() or None,
                    },
                )

    def s3_key(
        self,
        prefix: str,
        record: AttachmentRecord,
    ) -> str:
        # proposal/{proposalNumber}/{sequenceNumber}/{proposalAttachmentId}/{sanitizedFileName}
        name = sanitize_file_name(
            record.original_file_name,
            record.attachment_id,
        )
        parts = [
            prefix.strip("/"),
            record.attributes["business_key"],
            str(record.attributes["sequence_number"]),
            str(record.attachment_id),
            name,
        ]
        return "/".join(part for part in parts if part)

    def s3_object_metadata(
        self,
        record: AttachmentRecord,
        sha256: str,
    ) -> dict[str, str]:
        return {
            "sha256": sha256,
            "attachment-id": str(record.attachment_id),
            "proposal-id": str(record.record_id),
            "file-data-id": record.file_data_id or "",
        }

    def manifest_values(
        self,
        record: AttachmentRecord,
        bucket: str,
        key: str,
        *,
        byte_size: int | None,
        sha256: str | None,
        status: str,
        archived_timestamp: str | None,
        error_message: str | None,
    ) -> dict[str, Any]:
        return {
            "attachment_id": record.attachment_id,
            "proposal_id": record.record_id,
            "proposal_number": record.attributes["business_key"],
            "sequence_number": record.attributes["sequence_number"],
            "file_data_id": record.file_data_id,
            "original_file_name": record.original_file_name,
            "mime_type": record.mime_type,
            "s3_bucket": bucket,
            "s3_key": key,
            "byte_size": byte_size,
            "sha256": sha256,
            "archive_status": status,
            "archived_timestamp": archived_timestamp,
            "error_message": error_message,
            "manifest_updated_at": utc_now(),
        }

    def manifest_matches(
        self,
        manifest: dict[str, Any] | None,
        record: AttachmentRecord,
        bucket: str,
        key: str,
        byte_size: int,
        sha256: str,
    ) -> bool:
        if not manifest or manifest.get("archive_status") != "ARCHIVED":
            return False
        expected = self.manifest_values(
            record,
            bucket,
            key,
            byte_size=byte_size,
            sha256=sha256,
            status="ARCHIVED",
            archived_timestamp=manifest.get("archived_timestamp"),
            error_message=None,
        )
        for name in (
            "manifest_updated_at",
            "archived_timestamp",
            "archive_status",
            "error_message",
        ):
            expected.pop(name)
        return all(
            manifest.get(name) == value
            for name, value in expected.items()
        )

    def sync_postgres(
        self,
        manifest: ManifestStore | FlexibleManifestStore,
        record_id: int | None,
    ) -> int:
        """Unlike Subaward/Award (INSERT into a separate satellite
        table), this UPDATES the lifecycle columns already present on
        archive.proposal_attachment in place - the metadata row for a
        given proposal_attachment_id already exists (written by
        load_proposals_from_csv.py's upsert_proposal_attachments), this
        only ever advances its upload_status/s3_bucket/object_key/
        file_size/checksum/uploaded_at/error_message columns, never the
        metadata columns."""
        engine = create_postgres_engine()
        apply_migrations(
            engine,
            Path(__file__).resolve().parents[4]
            / "database"
            / "migrations",
        )

        update_sql = text(
            """
            UPDATE archive.proposal_attachment
               SET upload_status = :upload_status,
                   s3_bucket = :s3_bucket,
                   object_key = :object_key,
                   file_size = :file_size,
                   checksum = :checksum,
                   uploaded_at = :uploaded_at,
                   error_message = :error_message
             WHERE proposal_attachment_id = :proposal_attachment_id
            """
        )

        batch: list[dict[str, Any]] = []
        synced = 0
        with engine.begin() as connection:
            for row in manifest.rows(record_id):
                runner_status = row["archive_status"]
                upload_status = _RUNNER_STATUS_TO_UPLOAD_STATUS.get(
                    runner_status
                )
                if upload_status is None:
                    logger.warning(
                        "Skipping manifest row for attachment {} with "
                        "unrecognized archive_status {!r}",
                        row.get("attachment_id"),
                        runner_status,
                    )
                    continue

                batch.append(
                    {
                        "proposal_attachment_id": row["attachment_id"],
                        "upload_status": upload_status,
                        "s3_bucket": row.get("s3_bucket"),
                        "object_key": row.get("s3_key"),
                        "file_size": row.get("byte_size"),
                        "checksum": row.get("sha256"),
                        "uploaded_at": _parse_manifest_timestamp(
                            row.get("archived_timestamp")
                        ),
                        "error_message": row.get("error_message"),
                    }
                )
                if len(batch) == 500:
                    connection.execute(update_sql, batch)
                    synced += len(batch)
                    batch.clear()
            if batch:
                connection.execute(update_sql, batch)
                synced += len(batch)

        logger.info(
            "Synchronized {:,} manifest rows to archive.proposal_attachment",
            synced,
        )
        return synced

    def validate_counts(
        self,
        record_id: int | None,
        counts: ArchiveCounts,
    ) -> None:
        # Real fixture: Institutional Proposal 01157400, ACTIVE version
        # (proposal_id 1238613) - 5 real, distinct Kuali attachments
        # (Guidelines, Internal Budget, Internal Docs, Proposal
        # Package, Transfer Package) - live-verified against Oracle.
        if record_id == 1238613:
            if counts.attachment_metadata_count != 5:
                raise RuntimeError(
                    "Proposal 01157400 (proposal_id 1238613) validation "
                    "expected 5 attachment rows, got "
                    f"{counts.attachment_metadata_count}"
                )
            if counts.file_data_match_count != 5:
                raise RuntimeError(
                    "Proposal 01157400 (proposal_id 1238613) validation "
                    "expected 5 FILE_DATA matches, got "
                    f"{counts.file_data_match_count}"
                )

    def validate_sync_count(
        self,
        record_id: int | None,
        synced: int,
    ) -> None:
        if record_id == 1238613 and synced != 5:
            raise RuntimeError(
                "Proposal 01157400 (proposal_id 1238613) synchronization "
                f"expected 5 archived rows, got {synced}"
            )
