#!/bin/bash
# Installs the per-run TEST keys generated by scripts/identity-lab/start.sh
# (mounted read-only at /lab/creds), so none of the keys shipped in the image
# are used, then hands over to the image's own start-up.
set -euo pipefail
C=/opt/shibboleth-idp/credentials
for f in idp-signing.key idp-signing.crt idp-encryption.key idp-encryption.crt; do
  install -m 600 "/lab/creds/$f" "$C/$f"
done
mkdir -p /opt/certs
install -m 600 /lab/creds/idp-tls.key /opt/certs/idp-default.key
install -m 644 /lab/creds/idp-tls.crt /opt/certs/idp-default.crt
install -m 644 /lab/creds/sp-metadata.xml /opt/shibboleth-idp/metadata/lab-sp-metadata.xml
rm -f "$C/idp-backchannel.p12" "$C/idp-backchannel.crt" "$C/sealer.jks" "$C/sealer.kver"

SEALER_PW="$(head -c 24 /dev/urandom | base64 | tr -dc 'A-Za-z0-9')"
umask 077
cat > "$C/secrets.properties" <<PROPS
idp.sealer.storePassword = ${SEALER_PW}
idp.sealer.keyPassword = ${SEALER_PW}
idp.authn.LDAP.bindDNCredential = ${LAB_LDAP_READER_PASSWORD}
idp.attribute.resolver.LDAP.bindDNCredential = ${LAB_LDAP_READER_PASSWORD}
idp.persistentId.salt = ${LAB_PERSISTENT_ID_SALT}
PROPS
/opt/shibboleth-idp/bin/seckeygen.sh --storefile "$C/sealer.jks" --storepass "$SEALER_PW" \
  --versionfile "$C/sealer.kver" --alias secret >/dev/null
chown -R tomcat:tomcat "$C" 2>/dev/null || true
exec /usr/bin/startup.sh
