SET PAGESIZE 50000
SET LINESIZE 32767
SET FEEDBACK ON

SELECT
    a.AWARD_ID,
    a.AWARD_NUMBER,
    a.SEQUENCE_NUMBER,
    a.AWARD_SEQUENCE_STATUS,

    a.STATUS_CODE,
    s.DESCRIPTION AS STATUS_DESCRIPTION,

    a.TITLE,

    a.SPONSOR_CODE,
    sp.SPONSOR_NAME,

    a.PRIME_SPONSOR_CODE,
    psp.SPONSOR_NAME AS PRIME_SPONSOR_NAME,

    a.LEAD_UNIT_NUMBER,
    u.UNIT_NAME AS LEAD_UNIT_NAME,

    a.PROPOSAL_NUMBER,

    a.ACCOUNT_NUMBER,

    a.SPONSOR_AWARD_NUMBER,

    a.AWARD_EFFECTIVE_DATE,
    a.AWARD_EXECUTION_DATE,
    a.BEGIN_DATE,
    a.CLOSEOUT_DATE,

    a.TRANSACTION_TYPE_CODE,
    tt.DESCRIPTION AS TRANSACTION_TYPE,

    a.MODIFICATION_NUMBER,

    a.UPDATE_TIMESTAMP,
    a.UPDATE_USER,

    CASE
        WHEN a.SEQUENCE_NUMBER =
             MAX(a.SEQUENCE_NUMBER)
             OVER (PARTITION BY a.AWARD_NUMBER)
        THEN 'Y'
        ELSE 'N'
    END AS IS_CURRENT_VERSION

FROM AWARD a

LEFT JOIN AWARD_STATUS s
       ON s.STATUS_CODE = a.STATUS_CODE

LEFT JOIN SPONSOR sp
       ON sp.SPONSOR_CODE = a.SPONSOR_CODE

LEFT JOIN SPONSOR psp
       ON psp.SPONSOR_CODE = a.PRIME_SPONSOR_CODE

LEFT JOIN UNIT u
       ON u.UNIT_NUMBER = a.LEAD_UNIT_NUMBER

LEFT JOIN AWARD_TRANSACTION_TYPE tt
       ON tt.AWARD_TRANSACTION_TYPE_CODE = a.TRANSACTION_TYPE_CODE

ORDER BY
    a.AWARD_NUMBER,
    a.SEQUENCE_NUMBER;
