SET PAGESIZE 50000
SET LINESIZE 32767
SET FEEDBACK ON

SELECT
    aai.AWARD_AMOUNT_INFO_ID,
    aai.AWARD_ID,
    aai.AWARD_NUMBER,
    aai.SEQUENCE_NUMBER,

    aai.ANTICIPATED_CHANGE_DIRECT,
    aai.ANTICIPATED_CHANGE_INDIRECT,

    aai.ANTICIPATED_TOTAL_DIRECT,
    aai.ANTICIPATED_TOTAL_INDIRECT,

    aai.OBLIGATED_TOTAL_DIRECT,
    aai.OBLIGATED_TOTAL_INDIRECT,

    NVL(aai.ANTICIPATED_TOTAL_DIRECT, 0)
      + NVL(aai.ANTICIPATED_TOTAL_INDIRECT, 0)
        AS ANTICIPATED_TOTAL_AMOUNT,

    NVL(aai.OBLIGATED_TOTAL_DIRECT, 0)
      + NVL(aai.OBLIGATED_TOTAL_INDIRECT, 0)
        AS OBLIGATED_TOTAL_AMOUNT,

    aai.TNM_DOCUMENT_NUMBER,
    aai.VER_NBR

FROM AWARD_AMOUNT_INFO aai

ORDER BY
    aai.AWARD_NUMBER,
    aai.SEQUENCE_NUMBER,
    aai.AWARD_AMOUNT_INFO_ID;
