SET PAGESIZE 50000
SET LINESIZE 32767
SET FEEDBACK ON

SELECT
    ap.AWARD_PERSON_ID,
    ap.AWARD_ID,
    ap.AWARD_NUMBER,
    ap.SEQUENCE_NUMBER,

    ap.PERSON_ID,
    ap.ROLODEX_ID,
    ap.FULL_NAME,

    ap.CONTACT_ROLE_CODE,
    ap.KEY_PERSON_PROJECT_ROLE,

    ap.FACULTY_FLAG,

    ap.ACADEMIC_YEAR_EFFORT,
    ap.CALENDAR_YEAR_EFFORT,
    ap.SUMMER_EFFORT,
    ap.TOTAL_EFFORT,

    ap.UPDATE_TIMESTAMP,
    ap.UPDATE_USER

FROM AWARD_PERSONS ap

ORDER BY
    ap.AWARD_NUMBER,
    ap.SEQUENCE_NUMBER,
    ap.AWARD_PERSON_ID;
