SET PAGESIZE 50000
SET LINESIZE 32767
SET FEEDBACK ON

SELECT
    afp.AWARD_FUNDING_PROPOSAL_ID,
    afp.AWARD_ID,
    afp.PROPOSAL_ID,
    afp.ACTIVE,
    afp.UPDATE_TIMESTAMP,
    afp.UPDATE_USER,
    afp.VER_NBR

FROM AWARD_FUNDING_PROPOSALS afp

ORDER BY
    afp.AWARD_ID,
    afp.PROPOSAL_ID,
    afp.AWARD_FUNDING_PROPOSAL_ID;
